name: Schprocket Site
favicon: null
layout_spectrum: 0.5132132163271308
typography_spectrum: 0.92363321618177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.600892964983359
  lightness: 0.4226259517017752
  saturation: 0.01389790279790759
  rhythmicContrast: 0.9413985826540738
purpose: []
